### ISSUE TITLE
Thoughts about upstreaming?

### ISSUE THREAD

**Issue by antonialoytorrens** [hexdump0815/pmaports-amazon#1]
I've seen that the Amazon Ford and the Amazon Suez (based on the releases tab, I don't know if the other ports on master are functional) are two devices that don't exist in official postmarketOS pmaports.

It could be great if they get upstreamed, even if they use a downstream kernel, to get some extra visibility.
Regarding the other ports, you may submit them or send a patch if you get them working or you add extra functionality.

Best wishes,
Antoni Aloy Torrens

**Comment by hexdump0815** [comment]
hi antoni,

ford, austin, douglas and suez are working well enough, so that i should find some time to upstream them in the near future.

i also plan to work on and add giza, karnak, mustang and maybe sloane in the future too.

best wishes - hexdump

**Comment by antonialoytorrens** [comment]
Glad to know, thank you very much!
